Repository GUESS-ME-GDSC/Server, pull requests merged in 2023-05, with the labels that each got.

#76 [Feat] #74 에러 핸들링 로직 추가
  src/main/java/gdsc/mju/guessme/domain/auth/AuthController.java
  src/main/java/gdsc/mju/guessme/domain/info/InfoController.java
  src/main/java/gdsc/mju/guessme/domain/info/InfoService.java
  src/main/java/gdsc/mju/guessme/domain/info/dto/DeleteInfoByIdListReqDto.java
  src/main/java/gdsc/mju/guessme/domain/info/repository/InfoRepository.java
  src/main/java/gdsc/mju/guessme/domain/person/PersonController.java
  src/main/java/gdsc/mju/guessme/domain/person/PersonService.java
  src/main/java/gdsc/mju/guessme/domain/person/entity/Person.java
  src/main/java/gdsc/mju/guessme/domain/quiz/QuizController.java
  src/main/java/gdsc/mju/guessme/domain/quiz/QuizService.java
  src/main/java/gdsc/mju/guessme/domain/user/entity/User.java
Labels: enhancement

#77 Feat/#72 이전에 맞춘 quiz 연속 세번 틀리면 보호자에게 메일 전송
  build.gradle
  src/main/java/gdsc/mju/guessme/domain/info/entity/Info.java
  src/main/java/gdsc/mju/guessme/domain/person/entity/Person.java
  src/main/java/gdsc/mju/guessme/domain/quiz/QuizController.java
  src/main/java/gdsc/mju/guessme/domain/quiz/QuizService.java
  src/main/java/gdsc/mju/guessme/domain/quiz/dto/ScoreReqDto.java
  src/main/java/gdsc/mju/guessme/domain/quiz/entity/Scoring.java
  src/main/java/gdsc/mju/guessme/domain/quiz/repository/ScoringRepository.java
  src/main/resources/application.properties
  src/main/resources/templates/mail.html
Labels: enhancement

#79 [Feat] #71 #78 chat gpt 적용 및 scoring api 추가 작업
  src/main/java/gdsc/mju/guessme/domain/info/entity/Info.java
  src/main/java/gdsc/mju/guessme/domain/quiz/QuizController.java
  src/main/java/gdsc/mju/guessme/domain/quiz/QuizService.java
  src/main/java/gdsc/mju/guessme/domain/quiz/dto/ScoreReqDto.java
  src/main/java/gdsc/mju/guessme/domain/quiz/entity/Scoring.java
  src/main/java/gdsc/mju/guessme/domain/quiz/repository/ScoringRepository.java
  src/main/java/gdsc/mju/guessme/global/infra/openai/OpenAIRestTemplateConfig.java
  src/main/java/gdsc/mju/guessme/global/infra/openai/OpenAIService.java
  src/main/java/gdsc/mju/guessme/global/infra/openai/OpenAIServiceImpl.java
  src/main/java/gdsc/mju/guessme/global/infra/openai/dto/ChatRequest.java
  src/main/java/gdsc/mju/guessme/global/infra/openai/dto/ChatResponse.java
  src/main/java/gdsc/mju/guessme/global/infra/openai/dto/Choice.java
  src/main/java/gdsc/mju/guessme/global/infra/openai/dto/Message.java
  src/main/java/gdsc/mju/guessme/global/infra/openai/dto/Usage.java
  src/main/resources/application.properties
  src/test/java/gdsc/mju/guessme/domain/quiz/QuizServiceTest.java
  src/test/java/gdsc/mju/guessme/global/infra/openai/OpenAIServiceImplTest.java
Labels: enhancement

#81 [!HOTFIX] #80 info 수정 요청 시 발생하는 에러 수정
  src/main/java/gdsc/mju/guessme/domain/info/dto/InfoObj.java
  src/main/java/gdsc/mju/guessme/domain/person/dto/UpdatePersonReqDto.java
Labels: bug, enhancement

#82 [feat] #74 이미지에서 text detect 못할 시 400 반환
  src/main/java/gdsc/mju/guessme/domain/quiz/QuizService.java
Labels: enhancement

#87 [Feat] #84 필체 이미지 유사도 분석 관련 추가 작업
  src/main/java/gdsc/mju/guessme/domain/quiz/QuizService.java
  src/main/java/gdsc/mju/guessme/domain/quiz/dto/CompareImageResDto.java
  src/main/java/gdsc/mju/guessme/domain/quiz/entity/Scoring.java
Labels: documentation, enhancement
