Repository GUESS-ME-GDSC/Server, pull requests merged in 2023-03, with the labels that each got.

#2 Feat/#1 기능 명세서에 따라 Entity 구현
  src/main/java/gdsc/mju/guessme/domain/character/entity/Character.java
  src/main/java/gdsc/mju/guessme/domain/info/entity/Info.java
  src/main/java/gdsc/mju/guessme/domain/user/UserController.java
  src/main/java/gdsc/mju/guessme/domain/user/UserService.java
  src/main/java/gdsc/mju/guessme/domain/user/dto/BlahBlahReqDto.java
  src/main/java/gdsc/mju/guessme/domain/user/dto/BlahResDto.java
  src/main/java/gdsc/mju/guessme/domain/user/entity/User.java
  src/main/java/gdsc/mju/guessme/domain/user/repository/UserRepository.java
  src/main/java/gdsc/mju/guessme/global/response/Response.java
Labels: documentation, enhancement

#7 Feat/#6 Entity 및 DB 관련 추가 작업
  .gitignore
  .gitmessage.txt
  build.gradle
  src/main/java/gdsc/mju/guessme/GuessmeApplication.java
  src/main/java/gdsc/mju/guessme/domain/info/entity/Info.java
  src/main/java/gdsc/mju/guessme/domain/person/PersonController.java
  src/main/java/gdsc/mju/guessme/domain/person/PersonService.java
  src/main/java/gdsc/mju/guessme/domain/person/dto/PersonResDto.java
  src/main/java/gdsc/mju/guessme/domain/person/entity/Person.java
  src/main/java/gdsc/mju/guessme/domain/person/repository/PersonRepository.java
  src/main/java/gdsc/mju/guessme/domain/user/entity/User.java
  src/main/java/gdsc/mju/guessme/global/response/Response.java
  src/main/resources/application.properties
Labels: documentation, enhancement

#8 Feat/#6 Entity 및 DB 관련 추가 작업 develop으로 병합
  .gitignore
  .gitmessage.txt
  src/main/java/gdsc/mju/guessme/GuessmeApplication.java
  src/main/java/gdsc/mju/guessme/domain/info/entity/Info.java
  src/main/java/gdsc/mju/guessme/domain/person/PersonController.java
  src/main/java/gdsc/mju/guessme/domain/person/PersonService.java
  src/main/java/gdsc/mju/guessme/domain/person/dto/PersonResDto.java
  src/main/java/gdsc/mju/guessme/domain/person/entity/Person.java
  src/main/java/gdsc/mju/guessme/domain/person/repository/PersonRepository.java
  src/main/java/gdsc/mju/guessme/domain/user/entity/User.java
  src/main/java/gdsc/mju/guessme/global/response/Response.java
  src/main/resources/application.properties
Labels: documentation, enhancement

#11 Feat/#9 Response 객체 관련 작업
  src/main/java/gdsc/mju/guessme/domain/person/PersonController.java
  src/main/java/gdsc/mju/guessme/domain/person/PersonService.java
  src/main/java/gdsc/mju/guessme/global/response/BaseException.java
  src/main/java/gdsc/mju/guessme/global/response/BaseResponse.java
  src/main/java/gdsc/mju/guessme/global/response/ExceptionController.java
  src/main/java/gdsc/mju/guessme/global/response/Response.java
  src/main/resources/application.properties
Labels: enhancement

#12 Feat/#10 env file로 환경변수 처리
  .gitignore
  src/main/resources/application.properties
Labels: documentation, enhancement

#14 Feat/#13 jpa column default value 관련 버그 수정
  src/main/java/gdsc/mju/guessme/domain/info/dto/InfoObj.java
  src/main/java/gdsc/mju/guessme/domain/info/entity/Info.java
  src/main/java/gdsc/mju/guessme/domain/info/repository/InfoRepository.java
  src/main/java/gdsc/mju/guessme/domain/person/PersonController.java
  src/main/java/gdsc/mju/guessme/domain/person/PersonService.java
  src/main/java/gdsc/mju/guessme/domain/person/dto/CreatePersonReqDto.java
  src/main/java/gdsc/mju/guessme/domain/person/entity/Person.java
  src/main/java/gdsc/mju/guessme/domain/person/repository/PersonRepository.java
  src/main/java/gdsc/mju/guessme/domain/user/repository/UserRepository.java
  src/main/resources/application.properties
Labels: bug, enhancement

#20 Feat/#5 Quiz 도메인 API 구현
  src/main/java/gdsc/mju/guessme/domain/person/repository/PersonRepository.java
  src/main/java/gdsc/mju/guessme/domain/quiz/QuizController.java
  src/main/java/gdsc/mju/guessme/domain/quiz/QuizService.java
  src/main/java/gdsc/mju/guessme/domain/quiz/dto/CreateQuizResDto.java
  src/main/java/gdsc/mju/guessme/domain/quiz/dto/NewScoreDto.java
Labels: documentation, enhancement

#22 [Feat] #16 Info domain에 인물 정보 삭제 API 추가
  src/main/java/gdsc/mju/guessme/domain/info/InfoController.java
  src/main/java/gdsc/mju/guessme/domain/info/InfoService.java
  src/main/java/gdsc/mju/guessme/domain/info/dto/DeleteInfoByIdListReqDto.java
  src/main/java/gdsc/mju/guessme/domain/info/repository/InfoRepository.java
Labels: documentation, enhancement

#23 [Feat] #17 인물 추가 api에서 정보 추가 기능 삭제
  src/main/java/gdsc/mju/guessme/domain/person/PersonService.java
  src/main/java/gdsc/mju/guessme/domain/person/dto/CreatePersonReqDto.java
Labels: documentation, enhancement

#25 [Feat] #18 Request body의 property에 필요에 따라 null을 실을 수 있도록 함
  .gitignore
  Dockerfile
  src/main/java/gdsc/mju/guessme/domain/person/PersonController.java
  src/main/java/gdsc/mju/guessme/domain/person/PersonService.java
  src/main/java/gdsc/mju/guessme/domain/person/dto/CreatePersonReqDto.java
  src/main/java/gdsc/mju/guessme/domain/person/entity/Person.java
  src/main/resources/application.properties
Labels: documentation, enhancement

#28 [Feat] #27 유저 회원가입, 로그인 기능 구현
  build.gradle
  src/main/java/gdsc/mju/guessme/domain/auth/AuthController.java
  src/main/java/gdsc/mju/guessme/domain/auth/CustomUserDetailService.java
  src/main/java/gdsc/mju/guessme/domain/auth/config/WebSecurityConfig.java
  src/main/java/gdsc/mju/guessme/domain/auth/jwt/JwtAuthenticationFilter.java
  src/main/java/gdsc/mju/guessme/domain/auth/jwt/JwtTokenProvider.java
  src/main/java/gdsc/mju/guessme/domain/person/PersonService.java
  src/main/java/gdsc/mju/guessme/domain/user/entity/User.java
  src/main/java/gdsc/mju/guessme/domain/user/repository/UserRepository.java
  src/main/resources/application.properties
Labels: documentation, enhancement

#31 [Feat] #30 security
  build.gradle
  src/main/java/gdsc/mju/guessme/domain/auth/AuthController.java
  src/main/java/gdsc/mju/guessme/domain/auth/AuthService.java
  src/main/java/gdsc/mju/guessme/domain/auth/CustomUserDetailService.java
  src/main/java/gdsc/mju/guessme/domain/auth/UserDetailsServiceImpl.java
  src/main/java/gdsc/mju/guessme/domain/auth/config/WebSecurityConfig.java
  src/main/java/gdsc/mju/guessme/domain/auth/dto/AuthReqDto.java
  src/main/java/gdsc/mju/guessme/domain/auth/jwt/JwtAuthenticationFilter.java
  src/main/java/gdsc/mju/guessme/domain/auth/jwt/JwtTokenFilter.java
  src/main/java/gdsc/mju/guessme/domain/auth/jwt/JwtTokenProvider.java
  src/main/java/gdsc/mju/guessme/domain/user/entity/User.java
  src/main/java/gdsc/mju/guessme/global/config/JwtSecurityConfig.java
  src/main/java/gdsc/mju/guessme/global/config/SecurityConfig.java
  src/main/java/gdsc/mju/guessme/global/response/UserNotFoundException.java
  src/main/resources/application.properties
Labels: enhancement

#33 [Feat] #32 authorization
  src/main/java/gdsc/mju/guessme/domain/auth/AuthService.java
  src/main/java/gdsc/mju/guessme/domain/person/PersonController.java
  src/main/java/gdsc/mju/guessme/domain/person/PersonService.java
  src/main/java/gdsc/mju/guessme/domain/person/repository/PersonRepository.java
  src/main/java/gdsc/mju/guessme/domain/quiz/QuizController.java
  src/test/java/gdsc/mju/guessme/GuessmeApplicationTests.java
  src/test/java/gdsc/mju/guessme/domain/auth/AuthServiceTest.java
Labels: enhancement

#37 [Feat] #36 날짜 관련 타입의 직렬화
  src/main/java/gdsc/mju/guessme/domain/person/dto/CreatePersonReqDto.java
  src/main/java/gdsc/mju/guessme/domain/person/dto/UpdatePersonReqDto.java
Labels: bug, enhancement

#39 [Feat] #38 텍스트 추출 원격 이미지 사용으로 교체
  Dockerfile
  src/main/java/gdsc/mju/guessme/domain/quiz/QuizController.java
  src/main/java/gdsc/mju/guessme/domain/quiz/QuizService.java
  src/main/java/gdsc/mju/guessme/domain/quiz/dto/ScoreReqDto.java
Labels: enhancement

#41 [Feat] #40 gcs에 데이터 저장 후 반환하는 url 가공 부분 수정
  src/main/java/gdsc/mju/guessme/global/infra/gcs/GcsService.java
Labels: enhancement

#43 [Feat] #42 infoObj에 id property 추가
  src/main/java/gdsc/mju/guessme/domain/info/dto/InfoObj.java
Labels: documentation, enhancement

#45 [Feat] #44 PersonResDto에 favorite을 추가
  src/main/java/gdsc/mju/guessme/domain/person/dto/PersonResDto.java
Labels: documentation, enhancement

#47 [Feat] #46 CreateQuizResDto relation 필드 명 오타 수정
  src/main/java/gdsc/mju/guessme/domain/quiz/dto/CreateQuizResDto.java
Labels: enhancement

#49 [Feat] #48 Quiz 생성 API Response 변경
  src/main/java/gdsc/mju/guessme/domain/quiz/QuizController.java
  src/main/java/gdsc/mju/guessme/domain/quiz/QuizService.java
  src/main/java/gdsc/mju/guessme/domain/quiz/dto/CreateQuizResDto.java
  src/main/java/gdsc/mju/guessme/domain/quiz/dto/QuizDto.java
Labels: enhancement

#51 [feat] #50 퀴즈 생성 api response에 이미지, 음성 추가
  src/main/java/gdsc/mju/guessme/domain/quiz/QuizController.java
  src/main/java/gdsc/mju/guessme/domain/quiz/QuizService.java
  src/main/java/gdsc/mju/guessme/domain/quiz/dto/QuizResDto.java
Labels: enhancement

#52 [Feat] #21 GCP로의 배포
  Dockerfile
Labels: enhancement

#54 [feat] #53 ScoreReqDto에서 answer 필드 삭제
  src/main/java/gdsc/mju/guessme/domain/quiz/dto/ScoreReqDto.java
Labels: enhancement

#56 [Feat] #55 문제 생성 시 해당 인물의 점수도 같이 반환
  src/main/java/gdsc/mju/guessme/domain/quiz/QuizService.java
  src/main/java/gdsc/mju/guessme/domain/quiz/dto/QuizResDto.java
Labels: enhancement

#58 [feat] #57 문제 생성 시 인물 id 반환
  src/main/java/gdsc/mju/guessme/domain/quiz/QuizService.java
  src/main/java/gdsc/mju/guessme/domain/quiz/dto/QuizResDto.java
Labels: enhancement

#59 [feat] #55 문제 생성 시 반환값에 이전 점수 추가
  src/main/java/gdsc/mju/guessme/domain/quiz/QuizService.java
  src/main/java/gdsc/mju/guessme/domain/quiz/dto/QuizResDto.java
Labels: enhancement

#61 [Feat] #60 201에서 200으로 응답 상태코드 변경
  src/main/java/gdsc/mju/guessme/domain/info/InfoController.java
Labels: documentation

#63 [Feat] #62 README 파일 작성
  README.md
Labels: documentation

#70 [Docs] #69 이전 버전으로 복구
  README.md
Labels: documentation
